Stałe i annotacje
jgrodzki/pio_git_rhymers pull request #2
Opened 2023-04-26 19:12 UTC by MateuszKarbownik

2023-04-26 20:31 UTC, jgrodzki requested changes
PS. zapomniałeś skonfigurować swojego clone'a żeby używał twojego GitHubowego maila/username'a, przez co push został wykonany z twojego lokalnego konta (commity należą do mati2115). Ale nie wiem czy będą przez to problemy

2023-04-26 20:31 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public int compareIsFull = 11;
Deklaracje zmiennych powinny mieć sygnaturę public static final. Nazwy stałych powinny być pisane ALL CAPS z ewentualnymi podłogami. Nazwy stałych powinny być bardziej opisowe:
- sens stałej dotyczącej pola total może być określony przy pomocy następujących słów: EMPTY lub INITIAL, INDEX lub INDICATOR, RHYMER lub NUMBERS (np. EMPTY_RHYMER_INDICATOR),
- sens stałej dotyczącej domyślnej zwracanej wartości można określić za pomocą słów, np. IF_EMPTY lub DEFAULT, RETURN, VALUE (np. DEFAULT_VALUE).
- maksymalna liczba elementów w tablicy numbers nie może opisana za pomocą słów CAPACITY lub MAX_SIZE (samo SIZE jest niewłaściwe).

2023-04-26 20:31 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public int arraySize = 12;
Stałe związane z maksymalnym rozmiarem stosu (11 i 12) powinny być od siebie zależne (tak, żeby zmiana jednej wpływała odpowiednio na drugą).

2023-04-26 20:31 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int compareCallCheck = -1;
W klasie DefaultCountingOutRhymer stałe o wartości -1 odnoszące się do pola total (też w metodzie callCheck), to nie jest ta sama stała o wartości -1 oznaczające domyślną zwracaną przez wyliczankę wartość (w metodach peekaboo i countOut). Powinny to być osobne stałe.

2023-04-26 20:31 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/list/IntLinkedList.java
> +    public int error = -1;
Te same uwagi co do deklaracji stałych jak w DefaultCountingOutRhymer.

2023-04-26 20:31 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
>      private int[] numbers = new int[arraySize];
Modyfikator final powinien być dodany tylko w następujących miejscach:
- Node -> value
- DefaultCountingOutRhymer -> numbers
- FIFORhymer -> temp
- (Wprowadzone stałe zastępujące literały powinny mieć modyfikator final od początku, ponieważ są stałymi)

2023-04-27 09:17 UTC, MateuszKarbownik commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public int compareIsFull = 11;
Dlaczego public a nie private?

2023-04-27 09:24 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public int compareIsFull = 11;
Teoretycznie może być private, ale public static jest ok. bo można używać stałych klasy poza obiektem (są static, należą do klasy a nie obiektu). Private jest akceptowalne, public static final jest domyślnie dodawane jak używasz opcji Refactor w Intellij.

2023-04-27 09:31 UTC, MateuszKarbownik commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
>      private int[] numbers = new int[arraySize];
Nie wejdę w pliki które nie edytowałem, bo mam problem żeby się zalogować na to konto na intelij, nie zmienie final dla value i temp

2023-04-27 09:40 UTC, jgrodzki requested changes

2023-04-27 09:40 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public int INITIAL = -1;
INITIAL nie jest stałą. Zmienna total powinna zostać jak była, powinna powstać nowa stała przypisana do total.

2023-04-29 10:34 UTC, jgrodzki requested changes
W plikach Node.java i FIFORhymer brakuje keyword'a final przy zmiennych temp i value. Oprócz tego i wymienionych zmian wszystko wydaje się ok.

2023-04-29 10:34 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public final int ARRAY_SIZE = 12;
Dobrze żeby te 2 stałe były static jeżeli są publiczne.

2023-04-29 10:34 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +        return INITIAL == CHECK_RETURN_VALUE;
Tutaj powinniśmy porównywać zmienną total ze stałą INITIAL.

2023-04-29 10:34 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +    public static final int CHECK_RETURN_VALUE = -1;
CHECK_RETURN_VALUE i PEEKA_RETURN_VALUE znaczą w kodzie to samo, jedną z nich możnaby usunąć.

2023-04-29 10:34 UTC, jgrodzki commented on src/main/java/edu/kis/vh/nursery/list/IntLinkedList.java
> +    public final int NODE_IS_EMPTY = -1;
Tutaj też przydałby się static.

2023-05-03 17:52 UTC, merged